### PR TITLE
fix: move "zdog" to devDependencies

### PR DESCRIPTION
**Pull request by aleclarson**

### CODE REVIEW

**Comment by drcmda** [comment]
good changes, have to wait a little tho - zdog is not a module atm but made for script tag consumption 😐 the npm module that's out in the wild doesn't expose anything. that's why i pull from github and inline in rollup.

**Comment by aleclarson** [comment]
@drcmda Ah, that makes sense. :P

**Comment by boardfish** [comment]
> the npm module that's out in the wild doesn't expose anything

Wasn't that changed in the latest version?

**Comment by drcmda** [comment]
so it's in? i checked two days ago or something like that ... will try again.

**Pull request merged**
